export const ACTIONS = {
  CLOSE_CART: 'CLOSE_CART',
  OPEN_CART: 'OPEN_CART',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
};
